name: acier_fc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  #flutter_barcode_scanner: ^2.0.0
  mobile_scanner: ^7.1.2
  font_awesome_flutter: ^10.9.0
# Outros pacotes
cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true